import type { ReactNode } from "react";
import type { Severity } from "../types";

export function Card({ title, actions, children, className = "" }: { title?: ReactNode; actions?: ReactNode; children: ReactNode; className?: string }) {
  return (
    <section className={`rounded-lg border border-ink-700 bg-ink-900 ${className}`}>
      {(title || actions) && (
        <header className="flex items-center justify-between gap-3 border-b border-ink-700 px-4 py-2.5">
          <h2 className="text-sm font-semibold tracking-wide text-slate-300">{title}</h2>
          <div className="flex items-center gap-2">{actions}</div>
        </header>
      )}
      <div className="p-4">{children}</div>
    </section>
  );
}

export function Stat({ label, value, hint, accent }: { label: string; value: ReactNode; hint?: ReactNode; accent?: string }) {
  return (
    <div className="rounded-lg border border-ink-700 bg-ink-900 px-4 py-3">
      <div className="text-[11px] font-medium uppercase tracking-wider text-slate-500">{label}</div>
      <div className={`mt-1 text-2xl font-semibold tabular-nums ${accent ?? "text-slate-100"}`}>{value}</div>
      {hint && <div className="mt-0.5 text-xs text-slate-500">{hint}</div>}
    </div>
  );
}

export const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#f43f5e",
  high: "#f97316",
  medium: "#eab308",
  low: "#38bdf8",
  informational: "#94a3b8",
};

export function SeverityBadge({ severity }: { severity: Severity | null | undefined }) {
  if (!severity) return <span className="text-slate-600">-</span>;
  const c = SEVERITY_COLOR[severity];
  return (
    <span className="inline-flex items-center gap-1.5 rounded px-1.5 py-0.5 text-[11px] font-bold uppercase tracking-wide"
      style={{ color: c, backgroundColor: `${c}1a`, border: `1px solid ${c}55` }}>
      <span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: c }} />
      {severity}
    </span>
  );
}

export function Badge({ children, tone = "slate", title }: { children: ReactNode; tone?: "slate" | "green" | "amber" | "red" | "sky" | "violet"; title?: string }) {
  const tones = {
    slate: "border-ink-600 bg-ink-800 text-slate-300",
    green: "border-emerald-700/60 bg-emerald-900/30 text-emerald-300",
    amber: "border-amber-700/60 bg-amber-900/30 text-amber-300",
    red: "border-rose-700/60 bg-rose-900/30 text-rose-300",
    sky: "border-sky-700/60 bg-sky-900/30 text-sky-300",
    violet: "border-violet-700/60 bg-violet-900/30 text-violet-300",
  };
  return <span title={title} className={`inline-flex items-center rounded border px-1.5 py-0.5 text-[11px] font-medium ${tones[tone]}`}>{children}</span>;
}

/** Simulated data must never be mistaken for real telemetry. */
export function SimBadge({ simulated }: { simulated: boolean }) {
  return simulated ? <Badge tone="violet" title="Generated by SentinelForge demo mode - not real telemetry">SIMULATED</Badge> : null;
}

export function StatusBadge({ status }: { status: string }) {
  const tone = ({ active: "green", disabled: "amber", not_applicable: "slate", rejected: "red", superseded: "slate",
    delivered: "green", failed: "red", local: "sky" } as const)[status as "active"] ?? "slate";
  return <Badge tone={tone}>{status.replace("_", " ")}</Badge>;
}

export function Button({ children, onClick, variant = "default", disabled, type = "button", title }: {
  children: ReactNode; onClick?: () => void; variant?: "default" | "primary" | "ghost" | "danger"; disabled?: boolean; type?: "button" | "submit"; title?: string;
}) {
  const v = {
    default: "border-ink-600 bg-ink-800 text-slate-200 hover:bg-ink-700",
    primary: "border-transparent bg-brand text-ink-950 hover:brightness-110 font-semibold",
    ghost: "border-transparent text-slate-400 hover:text-slate-200 hover:bg-ink-800",
    danger: "border-rose-800 bg-rose-950/40 text-rose-300 hover:bg-rose-900/40",
  }[variant];
  return (
    <button type={type} title={title} disabled={disabled} onClick={onClick}
      className={`inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-sm transition disabled:cursor-not-allowed disabled:opacity-50 ${v}`}>
      {children}
    </button>
  );
}

export function Empty({ children }: { children: ReactNode }) {
  return <div className="rounded-md border border-dashed border-ink-700 px-4 py-8 text-center text-sm text-slate-500">{children}</div>;
}

export function ErrorNote({ error }: { error: string | null }) {
  return error ? <div className="rounded-md border border-rose-800 bg-rose-950/30 px-3 py-2 text-sm text-rose-300">{error}</div> : null;
}

export function Code({ children, className = "" }: { children: string; className?: string }) {
  return <pre className={`overflow-auto rounded-md border border-ink-700 bg-ink-950 p-3 font-mono text-xs leading-relaxed text-slate-300 ${className}`}>{children}</pre>;
}

export function KV({ rows }: { rows: [string, ReactNode][] }) {
  return (
    <dl className="grid grid-cols-[max-content_1fr] gap-x-4 gap-y-1.5 text-sm">
      {rows.map(([k, v]) => (
        <div key={k} className="contents">
          <dt className="text-slate-500">{k}</dt>
          <dd className="min-w-0 break-words text-slate-200">{v ?? <span className="text-slate-600">-</span>}</dd>
        </div>
      ))}
    </dl>
  );
}

export function Th({ children, className = "" }: { children?: ReactNode; className?: string }) {
  return <th className={`px-3 py-2 text-left text-[11px] font-semibold uppercase tracking-wider text-slate-500 ${className}`}>{children}</th>;
}

export function Td({ children, className = "" }: { children?: ReactNode; className?: string }) {
  return <td className={`px-3 py-2 align-top ${className}`}>{children}</td>;
}

export function Table({ head, children }: { head: ReactNode; children: ReactNode }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead className="border-b border-ink-700">{head}</thead>
        <tbody className="divide-y divide-ink-800">{children}</tbody>
      </table>
    </div>
  );
}

export function PageHeader({ title, subtitle, actions }: { title: string; subtitle?: ReactNode; actions?: ReactNode }) {
  return (
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3">
      <div>
        <h1 className="text-xl font-semibold text-slate-100">{title}</h1>
        {subtitle && <p className="mt-0.5 text-sm text-slate-500">{subtitle}</p>}
      </div>
      <div className="flex flex-wrap items-center gap-2">{actions}</div>
    </div>
  );
}

export const fmtTime = (iso: string | null | undefined) => (iso ? new Date(iso).toLocaleString() : "-");
export const fmtNum = (n: number | undefined | null) => (n ?? 0).toLocaleString();
