"""MITRE ATT&CK coverage report generated from rule metadata (Markdown + ATT&CK Navigator layer)."""

import json
from collections import defaultdict

from sentinelforge.rules.loader import LoadedRule

TACTIC_ORDER = ["reconnaissance", "resource-development", "initial-access", "execution", "persistence",
                "privilege-escalation", "defense-evasion", "credential-access", "discovery", "lateral-movement",
                "collection", "command-and-control", "exfiltration", "impact"]
SEV_SCORE = {"informational": 1, "low": 1, "medium": 2, "high": 3, "critical": 4}


def _mapped(rules: list[LoadedRule]) -> list[LoadedRule]:
    return sorted((r for r in rules if r.definition.mitre), key=lambda r: r.definition.id)


def coverage_markdown(rules: list[LoadedRule], tested: set[str]) -> str:
    by_tactic: dict[str, dict[str, list]] = defaultdict(lambda: defaultdict(list))
    for r in _mapped(rules):
        by_tactic[r.definition.mitre.tactic][r.definition.mitre.technique].append(r.definition)
    techniques = {r.definition.mitre.technique for r in _mapped(rules)}
    lines = [
        "# MITRE ATT&CK coverage",
        "",
        "Generated by `sentinelforge coverage export` from rule metadata. Do not edit by hand. CI fails if it is stale.",
        "",
        f"**{len(rules)} rules · {len(techniques)} techniques · {len(by_tactic)} tactics · "
        f"{sum(1 for r in rules if r.definition.id in tested)}/{len(rules)} rules with unit tests**",
        "",
        "A rule mapped to a technique means SentinelForge has *a* detection for *some* behaviour of that technique, "
        "not complete coverage of it.",
        "",
        "| Tactic | Technique | Rules |",
        "|---|---|---|",
    ]
    for tactic in sorted(by_tactic, key=lambda t: TACTIC_ORDER.index(t) if t in TACTIC_ORDER else 99):
        for tech in sorted(by_tactic[tactic]):
            ids = ", ".join(f"`{d.id}` {d.name} ({d.severity})" for d in by_tactic[tactic][tech])
            lines.append(f"| {tactic} | [{tech}](https://attack.mitre.org/techniques/{tech.replace('.', '/')}/) | {ids} |")
    unmapped = [r.definition.id for r in rules if not r.definition.mitre]
    if unmapped:
        lines += ["", f"Rules without an ATT&CK mapping: {', '.join(unmapped)}"]
    lines += ["", "Load `attack-navigator-layer.json` in the [ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/) "
              "for a heat-map (score = highest rule severity).", ""]
    return "\n".join(lines)


def navigator_layer(rules: list[LoadedRule]) -> str:
    techs: dict[str, dict] = {}
    for r in _mapped(rules):
        d = r.definition
        t = techs.setdefault(d.mitre.technique, {"score": 0, "rules": [], "tactic": d.mitre.tactic})
        t["score"] = max(t["score"], SEV_SCORE[d.severity])
        t["rules"].append(d.id)
    layer = {
        "name": "SentinelForge detection coverage",
        "versions": {"layer": "4.5", "navigator": "5.1.0"},
        "domain": "enterprise-attack",
        "description": "Generated from SentinelForge rule packs. Score = highest severity of the rules mapped to the technique.",
        "gradient": {"colors": ["#fde68a", "#f97316", "#dc2626"], "minValue": 1, "maxValue": 4},
        "techniques": [{"techniqueID": k, "tactic": v["tactic"], "score": v["score"], "comment": ", ".join(v["rules"]),
                        "enabled": True} for k, v in sorted(techs.items())],
    }
    return json.dumps(layer, indent=2) + "\n"
